import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portafolio - JordanDev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Jordán Jaramillo</h1>

        <p className={styles.description}>
          Desarrollador FullStack <code className={styles.code}>Js - Php</code>
        </p>

        <div className={styles.grid}>
          <a href="/proyects" className={styles.card}>
            <h2>Proyectos 🚀 &rarr;</h2>
            <p>
              Te enseñaré los proyectos que he realizado a lo largo de mi
              carrera.
            </p>
          </a>

          <a href="/aboutme" className={styles.card}>
            <h2>Sobre mí 😀 &rarr;</h2>
            <p>
              Te contaré más de como invierto mi tiempo y lo que me gusta hacer
              en mis tiempos libres!
            </p>
          </a>

          <a
            href="/blog"
            className={styles.card}
          >
            <h2>Blog 📒 &rarr;</h2>
            <p>
              Te comparto algunas mini-guias sobre técnicas que he aprendido en
              mi carrera de desarrollador
            </p>
          </a>

          <a
            href="https://linkedin.com/in/jordandev" target="_blank" 
            className={styles.card}
          >
            <h2>Contáctame 📲 &rarr;</h2>
            <p>
              Puedes hablarme por medio de mi perfil de Linkedin será un gusto
              trabajar contigo.
            </p>
          </a>
        </div>
      </main>
    </div>
  );
}
